/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package javaprojectcleintside;

import common.user;
import java.awt.Point;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author ewess
 */
public class AddToChat extends javax.swing.JFrame {
    Vector<user> contacts;
    Vector<String> UsersName;
    Controller controller;
    user client;
    /**
     * Creates new form AddToChat
     */
    public AddToChat(Point point,Controller c,user user) {
        initComponents();
        setLocation(point);
        controller=c;
        client=user;
        contacts=controller.getContactList(user);
        UsersName=new Vector<String>();
        for(int i=0;i<contacts.size();i++){
            UsersName.add(contacts.get(i).getUserName());
        }
        contactsList.setListData(UsersName);
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactsList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        startChatButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(270, 360));
        setMinimumSize(new java.awt.Dimension(270, 360));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(270, 360));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentMoved(evt);
            }
        });

        contactsList.setBackground(new java.awt.Color(255, 255, 178));
        contactsList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(contactsList);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Start New Chat");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 250, 310);

        startChatButton.setText("start chat");
        startChatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startChatButtonActionPerformed(evt);
            }
        });
        getContentPane().add(startChatButton);
        startChatButton.setBounds(150, 320, 79, 23);

        cancelButton.setText("cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(60, 320, 81, 23);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 270, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1ComponentMoved

    private void startChatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startChatButtonActionPerformed
        System.out.println("inside start chat");
        ArrayList<String> chatMembers=new ArrayList<String>();
        ArrayList<String> chatMembersEmails=new ArrayList<String>();
       try{
           Object[] members= contactsList.getSelectedValues();
           for(int i=0;i<members.length;i++){
               System.out.println(members[i].toString());
               chatMembers.add(members[i].toString());
           }
           for(int i=0;i<chatMembers.size();i++){
               for(int j=0;j<contacts.size();j++){
                   System.out.println("inside for loop");
                   System.out.println("member :"+contacts.get(j).getEmail()+contacts.get(j).getUserName());
                   if(chatMembers.get(i).equals(contacts.get(j).getUserName())){
                       chatMembersEmails.add(contacts.get(j).getEmail());
                      
                   }
               }
           }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "please select friend from list first");
       }
        System.out.println("chat members are : "+chatMembers);
        System.out.println("chat membersemails are"+chatMembersEmails);
        controller.start_chat_session(chatMembersEmails);
        dispose();
    }//GEN-LAST:event_startChatButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList contactsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startChatButton;
    // End of variables declaration//GEN-END:variables
public static void main(String[] args) {
       
    }
}
